[package]
name = "sirt"
version = "0.1.1"
edition = "2024"

[dependencies]
libsirt = { path = "../libsirt" }

clap = {  version = "4.5.54", features = ["derive"] }
ratatui = "0.30.0"

serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
color-eyre = "0.6.5"
iced = "0.14.0"
